CREATE TABLE [dbo].[tenant]
(
  [id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1,1),
  [key] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
  [name] NVARCHAR(1024) NOT NULL,
  [enabled] BIT NOT NULL DEFAULT 1,
  [date_created] DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
  [date_modified] DATETIME2 NOT NULL DEFAULT GETUTCDATE()
)

